### ISSUE TITLE
手动按键打断[按下状态]的问题

### ISSUE THREAD

**Issue by coralfox** [WeijieH/D3keyHelper#1]
我看你的的代码里,
如果按下不放了,数组keysOnHold 里相应键值赋值为 1

但因为有事后得手动操作下,特别是鼠标左键,这个键又是交互键....
如果按了后,相当于,左键弹起,然后执行左键单击1次,但代码里还是记录它为按下状态

我觉得需要考虑按下1234 ,左键,右键的处理(设置为按下不放时),将keysOnHold重设为0
然后按下的处理需要做个循环心跳检测

或者是做个循环补按的操作,强制弹起,再强制按下...因为有时候左键的跑动和战斗判断很诡异

**Comment by WeijieH** [comment]
> 我看你的的代码里,
> 如果按下不放了,数组keysOnHold 里相应键值赋值为 1
> 
> 但因为有事后得手动操作下,特别是鼠标左键,这个键又是交互键....
> 如果按了后,相当于,左键弹起,然后执行左键单击1次,但代码里还是记录它为按下状态
> 
> 我觉得需要考虑按下1234 ,左键,右键的处理(设置为按下不放时),将keysOnHold重设为0
> 然后按下的处理需要做个循环心跳检测
> 
> 或者是做个循环补按的操作,强制弹起,再强制按下...因为有时候左键的跑动和战斗判断很诡异

keysOnHold我本意是想弄成一个类似python中set的Hashtable的，它只存储有哪些键被设置成保持按下状态。但是ahk好像没有这种数据类型，最接近的就是一个类似于dict的字典类型。所以它的值为0或者是1无所谓，只要这个key在里面，它就应该是保持按下的状态。
在StopMarco里面我会把keysOnHold里存储的键值一一弹出，然后取消掉下压状态。
你是把左键设置为了一直按下后遇到问题了吗？

**Comment by WeijieH** [comment]
issue因为没有收到后续回复所以我先关闭了
