### ISSUE TITLE
使用仅按下启动宏会触发的BUG

### ISSUE THREAD

**Issue by leftbrave** [WeijieH/D3keyHelper#19]
设置成按下鼠标右键触发，游戏内用右键穿装备和右键修改技能符文的时候会施放设置成连点的技能，用右键往物储物箱存放物品时除了会放技能还会在储物箱右上角搜索框输入字符，不知道是我设置有问题还是BUG，这是我的设置[](url)
![捕获](https://user-images.githubusercontent.com/36067951/127123813-54824dbe-771c-4169-b54b-81012730f5f9.PNG)

**Comment by leftbrave** [comment]
哦对了，用右键改技能符文的时候也会放设置成连点栋技能

**Comment by WeijieH** [comment]
这应该是正常行为，因为你按了右键所以在那一瞬间宏是启动的，启动的宏会向游戏中发送这些按键。

**Comment by leftbrave** [comment]
> 这应该是正常行为，因为你按了右键所以在那一瞬间宏是启动的，启动的宏会向游戏中发送这些按键。

我记得以前的版本没有这种问题。。。所以这个有办法解决吗大佬？

**Comment by WeijieH** [comment]
去看下最新的dev分支，0728版本。我在配置文件中加了个runonstart选项，改成0就应该是老版本的行为了。

**Comment by leftbrave** [comment]
> 去看下最新的dev分支，0728版本。我在配置文件中加了个runonstart选项，改成0就应该是老版本的行为了。

好的，谢谢大佬~

**Comment by WeijieH** [comment]
> > 去看下最新的dev分支，0728版本。我在配置文件中加了个runonstart选项，改成0就应该是老版本的行为了。
> 
> 好的，谢谢大佬~

没问题我就先close了，还有问题你再开
