### ISSUE TITLE
助手宏动画速度为非常快时分解助手漏过装备

### ISSUE THREAD

**Issue by raytracesoak** [WeijieH/D3keyHelper#20]
![快速分解issue](https://user-images.githubusercontent.com/18105970/127182263-487f0643-d4f9-4265-a8a1-3825982c5e4d.png)
位置31/32/51为单格物品时大概率被遗漏。

**Comment by WeijieH** [comment]
你游戏分辨率是多少？

**Comment by raytracesoak** [comment]
> 你游戏分辨率是多少？

1920*1080,按键发送模式input

**Comment by raytracesoak** [comment]
我攒攒装备看下每一格都是单格装备是什么结果。

**Comment by WeijieH** [comment]
> 我攒攒装备看下每一格都是单格装备是什么结果。

你可以试试dev下的版本，刚刚push了一个commit。之前的算法确实换了分辨率可能会不太准。

**Comment by raytracesoak** [comment]
感谢回复，又试了几遍发现几个点：
1. Event模式貌似因为动画速度比Input慢一点完全不会漏。
2. Input模式最快速度dev版会好一些，偶尔还是会漏，说不定是暗黑3游戏自己的问题。
3. 这个问题和单格装备无关，和那几个位置有关。

决定使用Event模式了
