### ISSUE TITLE
设置宏启动方式为仅按下时，按住启动快捷键不放会出现鼠标无法移动的现象。

### ISSUE THREAD

**Issue by wxzForest** [WeijieH/D3keyHelper#29]
![image](https://user-images.githubusercontent.com/18545797/137104235-d64610d6-9c65-4ec4-9c60-635e04798859.png)

玩武僧的时候设置宏启动方式为仅按下时，如上图设置，按住启动快捷键不放会出现鼠标无法移动的现象。松开快捷键后技能还要继续释放一段时间才结束，结束后鼠标才可以移动。

**Comment by WeijieH** [comment]
因为没有收到回复 所以先关闭了
