### ISSUE TITLE
功能还在开发中么？

### ISSUE THREAD

**Issue by youwi** [WeijieH/D3keyHelper#30]
能智能识别地上发光装备么？
金色装备和传奇外围有一圈光环

我对图例操作不熟，搞不定。。。

**Comment by WeijieH** [comment]
目前的几个画面识别都是针对个别像素点的RGB颜色值的简单判断. 更复杂的一些, 比如识别地上装备, 识别文字之类的, AHK做不到.
你要识别地上的装备, 是为了快速捡起来吗?

**Comment by WeijieH** [comment]
没有收到后续回复，先关闭了。
