### ISSUE TITLE
空格支持和shift+左键支持

### ISSUE THREAD

**Issue by KnifeFlyLittleLee** [WeijieH/D3keyHelper#39]
技能键能支持空格不，还有希望能加入shift+左键的支持，因为有时候buff类技能例如复仇一类的可能会放到左键还有割裂这种，放到左键如果连击的话有时候会走位

**Comment by WeijieH** [comment]
空格可以支持的，只不过要自己修改配置文件。可以参照这个视频https://www.bilibili.com/video/BV1Z64y1975X
左键目前的逻辑是这样的，如果是连点就简单的鼠标左键连点。但是如果是保持buff就等于按住shift同时左键连点。

**Comment by WeijieH** [comment]
没有后续回复 先关闭了
