### ISSUE TITLE
重铸功能能用吗

### ISSUE THREAD

**Issue by qqssff** [WeijieH/D3keyHelper#41]
试了下没反应，是我没操作对吗？

**Comment by WeijieH** [comment]
鼠标需要指向装备 你是不是凭空就按了

**Comment by qqssff** [comment]
> 鼠标需要指向装备 你是不是凭空就按了

指向装备了，按F5装备被点起来就没反应了

**Comment by WeijieH** [comment]
那就是重铸的界面没有识别到。你是窗口模式还是全屏模式？屏幕是双屏或者HDR的吗？
你可以试试窗口/全屏之间切换下。另外重铸的时候装备最好放到背包的右边格子里，因为左边的格子弹出的鼠标提示会挡住一些去色点。

**Comment by qqssff** [comment]
> 那就是重铸的界面没有识别到。你是窗口模式还是全屏模式？屏幕是双屏或者HDR的吗？ 你可以试试窗口/全屏之间切换下。另外重铸的时候装备最好放到背包的右边格子里，因为左边的格子弹出的鼠标提示会挡住一些去色点。

谢谢~放右边格子没问题了，就是选择重铸到远古太古没用，到远古也会继续重铸，感谢大佬解答

**Comment by WeijieH** [comment]
如果是窗口模式，某些分辨率下会有这种情况。全屏或者换个分辨率就行。

**Comment by qqssff** [comment]
> 如果是窗口模式，某些分辨率下会有这种情况。全屏或者换个分辨率就行。

好的，谢谢
