### ISSUE TITLE
自动药水会发送q到其他窗口，并且一旦开启无法关闭

### ISSUE THREAD

**Issue by EFrostBlade** [WeijieH/D3keyHelper#45]

**Comment by WeijieH** [comment]
检查下配置文件中d3only是否为默认的1

**Comment by EFrostBlade** [comment]
> 检查下配置文件中d3only是否为默认的1

是的，而且不止我一个出现这种问题，b站评论有好几个

**Comment by WeijieH** [comment]
游戏是窗口还是全屏模式运行的？这个问题每次用宏都出现吗还是只是偶尔？
我这边从来没碰到过这个问题。如果可能的话请详细描述下导致bug的操作，我需要能在本地复现才能有解决的思路。

**Comment by WeijieH** [comment]
试下0301版。打包好的exe在百度盘里，源代码在dev分支下。
